def build(bld):
  bld(features     = 'cxx cprogram',
      source       = 'lsaMain.cpp lsa.cpp',
      target       = 'lsa',
      install_path = None,
      includes     = '.',
      uselib_local = 'redsvd')
  bld(features     = 'cxx cprogram',
      source       = 'mclinearMain.cpp mclinear.cpp',
      target       = 'mclinear',
      install_path = None,
      includes     = '.',
      uselib_local = 'redsvd')

